package site.xulian.learning.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecordStatistics<M extends BaseRecordStatistics<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStudentId(java.lang.String studentId) {
		set("student_id", studentId);
	}

	public java.lang.String getStudentId() {
		return get("student_id");
	}

	public void setStudentName(java.lang.String studentName) {
		set("student_name", studentName);
	}

	public java.lang.String getStudentName() {
		return get("student_name");
	}

	public void setCreateTimes(java.lang.Integer createTimes) {
		set("create_times", createTimes);
	}

	public java.lang.Integer getCreateTimes() {
		return get("create_times");
	}

	public void setReplyTimes(java.lang.Integer replyTimes) {
		set("reply_times", replyTimes);
	}

	public java.lang.Integer getReplyTimes() {
		return get("reply_times");
	}

	public void setSumTimes(java.lang.Integer sumTimes) {
		set("sum_times", sumTimes);
	}

	public java.lang.Integer getSumTimes() {
		return get("sum_times");
	}

	public void setAskTimes(java.lang.Integer askTimes) {
		set("ask_times", askTimes);
	}

	public java.lang.Integer getAskTimes() {
		return get("ask_times");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
