package site.xulian.learning.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("answer", "id", Answer.class);
		arp.addMapping("record_statistics", "id", RecordStatistics.class);
		arp.addMapping("records", "id", Records.class);
		arp.addMapping("student", "id", Student.class);
		arp.addMapping("teacher", "id", Teacher.class);
		arp.addMapping("topic", "id", Topic.class);
		arp.addMapping("user", "id", User.class);
	}
}

