package site.xulian.learning.model;

import com.jfinal.kit.JsonKit;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;
import site.xulian.learning.model.base.BaseTeacher;
import site.xulian.learning.utils.Common;
import site.xulian.learning.utils.DataObj;
import site.xulian.learning.utils.MD5Salt;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacher extends BaseTeacher<Teacher> {
	public static final Teacher dao = new Teacher().dao();
	Logger logger = Logger.getLogger(this.getClass());
	/**
	 * 分页获取数据
	 *
	 * @param teacher_id
	 * @param pageSize
	 * @param orderBy
	 * @param isASC
	 * @return
	 */
	public Page<Teacher> getData(String teacher_id, int pageNum, int pageSize, String orderBy, boolean isASC) {
		logger.info("teacher_id:" +teacher_id);
		List<Object> params = new ArrayList<Object>();
		StringBuffer sql = new StringBuffer();
		sql.append("FROM teacher WHERE 1=1 AND status != -5 ");
		if (StringUtils.isNotBlank(Common.nullToBlank(teacher_id))) {
			sql.append("AND teacher_id like ? ");
			params.add(Common.queryLike(teacher_id));
		}
		orderBy = StrKit.isBlank(orderBy) ? "create_time" : orderBy;
		sql.append("ORDER BY " + orderBy + " " + (isASC ? "" : "DESC "));
		logger.info(sql.toString());
		return paginate(pageNum, pageSize, "SELECT * ", sql.toString(), params.toArray());
	}

	/**
	 * 删除数据
	 */
	public DataObj<String> delete(String[] ids) {
		logger.info("编号信息" + ids);
		StringBuffer sql = new StringBuffer();
		sql.append("UPDATE teacher SET status = -5 , update_time = now()");
		sql.append("WHERE id in (");
		sql.append(Common.arrayToSqlIn(ids));
		sql.append(")");
		Integer num = Db.update(sql.toString());
		if (num > 0) {
			return DataObj.getSuccessData("");
		}
		return new DataObj<>("删除老师信息失败！");
	}

	/**
	 * 保存数据
	 */
	public DataObj<Teacher> saveTeacher(Teacher teacher) {
		logger.info("保存数据" + JsonKit.toJson(teacher));
		try {
			boolean success = false;
			if (null == teacher.getId()) {
				User user = new User();
				teacher.setCreateTime(new Date());
				teacher.setUpdateTime(new Date());
				success = teacher.save();
				user.setName(teacher.getTeacherId());
				user.setPwd(MD5Salt.md5("123456"));
				user.setType(1);
				user.setCreateTime(new Date());
				user.setUpdateTime(new Date());
				user.save();
			} else {
				teacher.setUpdateTime(new Date());
				success = teacher.update();
			}
			if (!success) {
				return new DataObj<>("保存数据失败，稍后请重试");
			}
		} catch (Exception e) {
			logger.warn("保存老师数据异常", e);
			return new DataObj<>("添加数据失败，稍后请重试");
		}
		return DataObj.getSuccessData(teacher);
	}
	/**
	 * 批量插入学号信息
	 * */
	public DataObj<String> bathAdd(final List<String[]> list) {
		logger.info("老师信息: "+ JsonKit.toJson(list));
		final Record record = new Record();
		boolean isSuccess = Db.tx(new IAtom() {
			@Override
			public boolean run() throws SQLException {
				try{
					StringBuilder sql = new StringBuilder();
					StringBuilder sql_1 = new StringBuilder("INSERT INTO user(name,pwd,type,create_time,update_time) VALUES");
					List<Object> parmas =new ArrayList<Object>();
					List<Object> parmas_1 =new ArrayList<Object>();
					sql.append("INSERT INTO teacher(name,phone,sex,teacher_id,update_time,create_time) VALUES");
					for (int i = 1; i < list.size() ; i++) {//从第二行开始遍历 去除列表名
						sql_1.append("(?,?,?,now(),now()),");
						parmas_1.add(list.get(i)[3]);
						parmas_1.add(MD5Salt.md5("123456"));
						parmas_1.add(1);
						sql.append("(?,?,?,?,now(),now()),");
						saveFlowCoupon(list.get(i)[0],list.get(i)[1],list.get(i)[2],list.get(i)[3],parmas);
					}
					Db.update(sql.deleteCharAt(sql.length()-1).toString(),parmas.toArray());
					Db.update(sql_1.deleteCharAt(sql_1.length()-1).toString(),parmas_1.toArray());
//					Db.update("INSERT user(name,pwd,type,create_time,updtae_time) VALUES");
				}catch(Exception e){
					logger.info("插入错误: "+e.getMessage());
					record.set("msg", "插入失败,请重新上传");
					return false;
				}
				return true;
			}
		});
		if(isSuccess){
			return DataObj.getSuccessData("");
		}
		return new DataObj<String>(record.get("msg").toString());
	}

	/**
	 * 保存学生数据
	 * @throws ParseException
	 * */
	private void saveFlowCoupon(String name, String phone, String sex, String teacher_id, List<Object> parmas) throws ParseException{
		parmas.add(Common.nullToBlank(name));
		parmas.add(Common.nullToBlank(phone));
		parmas.add(Integer.parseInt(sex));
		parmas.add(teacher_id);
	}
}
